// This file is generated by npm run build:icons
 
export type IconName =
	| "ball"
	| "CgMediaLive"
	| "default-team"
	| "FaAngleDoubleUp"
	| "FcRating"
	| "GiBabyfootPlayers"
	| "GiCaptainHatProfile"
	| "GiSoccerKick"
	| "IoIosArrowDropright"
	| "IoIosStats"
	| "logo"
	| "logotype"
	| "MdCalendarMonth"
	| "MdOutlinePlace"
	| "MdOutlineStadium"
	| "MdSports"
	| "penalty"
	| "red-card"
	| "substitution"
	| "var"
	| "yellow-card";
