import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { cn } from '@/lib/utils';

import './globals.css';
import Providers from './providers';

const baseFont = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'SportHub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', baseFont.variable)}>
        <div className="flex h-screen flex-col">
          <Header />
          <Providers>
            <main className="grow">{children}</main>
          </Providers>
          <Footer />
        </div>
      </body>
    </html>
  );
}
